format = """
[](#B54BBB)\
$os\
$username\
[](fg:#B54BBB bg:#FF758E)\
$directory\
[](fg:#FF758E bg:#FFB366)\
$git_branch\
$git_status\
[](fg:#FFB366 bg:#00BFFF)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$python\
$rust\
$scala\
[](fg:#00BFFF bg:#4A90E2)\
$time\
[](fg:#4A90E2)\
$cmd_duration\
[\n  ](fg:#7FFF7F)\
"""
#  #9A348E
# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#B54BBB fg:#FFFFFF bold"
style_root = "bg:#B54BBB fg:#FFFFFF bold"
format = '[$user ]($style)'
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#B54BBB"
disabled = true # Disabled by default

[directory]#FF758E #DA627D
style = "bg:#FF758E fg:#FFFFFF bold"
format = "[ $path ]($style)"
truncation_length = 5
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[c]
symbol = " "
style = "bg:#00BFFF fg:#FFFFFF"
format = '[ $symbol ]($style)'

[docker_context]
symbol = " "
style = "bg:#86BBD8 fg:#FFFFFF"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#00BFFF fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#00BFFF fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FFB366 fg:#FFFFFF bold"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FFB366 fg:#FFFFFF bold"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#00BFFF fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#00BFFF fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#00BFFF fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "bg:#00BFFF fg:#FFFFFF bold"
format = '[ $symbol ]($style)'

[julia]
symbol = " "
style = "bg:#00BFFF fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#00BFFF fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#00BFFF fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "bg:#00BFFF fg:#FFFFFF"
format = '[ $symbol ]($style)'

[rust]
symbol = ""
style = "bg:#00BFFF fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#00BFFF fg:#FFFFFF"
format = '[ $symbol ($version) ]($style)'

[time] #33658A
disabled = false
time_format = "%I:%M %p" # Hour:Minute AM/PM Format
style = "bg:#4A90E2 fg:#FFFFFF bold"
format = '[ ♥ $time ]($style)'

[cmd_duration]
style = " fg:#00FF00 bold"
format = '[   $duration ]($style)'
min_time = 300